---
- name: Deployment POC
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Download ROOT.war
      ansible.builtin.get_url:
        url: http://example.com/path/ROOT.war
        dest: /path/to/save/ROOT.war
        username: your_username
        password: your_password
      delegate_to: localhost
      #Stop application
    - name: Return motd to registered var
      ansible.builtin.command: /bin/shutdown.sh
    - name: Check running processes
      shell: ps -ef | grep -i java
      register: ps_cmd
    - name: Show captured processes
      debug:
        var: ps_cmd.stdout
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /srv/myfiles/foo.conf
        dest: /etc/foo.conf
        owner: foo
        group: foo
        mode: '0644'
    - name: Get stats of a file
      ansible.builtin.stat:
        path: /path/to/save/ROOT.war
      register: stat
    - name: Debug
      ansible.builtin.debug:
        var: stat
    #Start Service
    - name: Return motd to registered var
      ansible.builtin.command: /bin/startup.sh
    - name: Check running processes
      shell: ps -ef | grep -i java
      register: ps_cmd_start
    - name: Show captured processes
      debug:
        var: ps_cmd_start.stdout
#/bin/shutdown.sh -> servis stop
#/bin/startup.sh -> servis start
