---
- name: Append group4 to Addgroups line in sshd_config
  hosts: 192.168.22.120
  become: true
  vars:
    group_name: group3
  tasks:

    - name: Get current AllowGroups line
      command: grep '^AllowGroups' /etc/ssh/sshd_config
      register: match_AllowGroups
      changed_when: false
      ignore_errors: true
  
    - name: Add group_name to AllowGroups line
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^AllowGroups'
        line: "{{ (match_AllowGroups.stdout_lines[0] if match_AllowGroups.stdout_lines else 'AllowGroups') + ' {{ group_name }}' }}"
        backrefs: yes
      when: "group_name not in match_AllowGroups.stdout_lines[0]"

    - name: Restart SSH service
      service:
        name: sshd
        state: restarted
      when: "group_name not in match_AllowGroups.stdout_lines[0]"
