##########     Maintener -> Altuğ Yıldırım, Osman Emre Çelik              ####################
##########     Maintener Company -> QUASYS Digital Technology Solutions   ####################
##########     PCC Defender Deployment Automation                         ####################
##########     Prereqs: Creating twistlock namespace before deployment    ####################
---
- name: Configure OpenShift and Twistlock settings
  hosts: AAP-HybridNode
  gather_facts: false
  vars:
    twistlock:
      username: "{{ lookup('ansible.builtin.env', 'TWISTLOCK_USERNAME') }}"
      password: "{{ lookup('ansible.builtin.env', 'TWISTLOCK_PASSWORD') }}"
    twistlock_console: "ec2-34-215-144-89.compute-1.amazonaws.com:8083" #sabit
    twistlock_defender: "ec2-34-215-144-89.compute-1.amazonaws.com:8084" #sabit
    apiversion: "v1" #sabit
    namespace: "test-qua-twistlock"  # sabit
    defender_version: "32"  # Define your defender version
    repo: jfrog.xyz/defender

  tasks:
    - name: Set facts for each oc_server
      set_fact:
        cluster_name: "{{ oc_server.split('.')[1] }}"

    - name: Defenders - Deploy - DaemonSet - Get Defender yaml
      ansible.builtin.uri:
        url: https://{{ twistlock_console }}/api/{{ apiversion }}/defenders/daemonset.yaml
        method: POST
        body: {
                "consoleAddr": "{{ twistlock_defender }}",
                "cluster": "{{ cluster_name }}",
                "namespace": "{{ namespace }}",
                "orchestration": "openshift",
                "containerRuntime": "crio",
                "privileged": false,
                "serviceaccounts": true,
                "istio": false,
                "collectPodLabels": true,
                "memoryLimit": 2000,
                "cpuLimit": 1500,
                #"image": "{{ repo }}:{{ defender_version }}",
                "selinux": true
                }
        user: "{{ twistlock.username }}"
        password: "{{ twistlock.password }}"
        dest: defender-ds.yaml
        mode: 0755
        force_basic_auth: yes
        validate_certs: no
        body_format: json
        status_code: 200
      register: result
      until: result.status == 200
      retries: 1
      delay: 10

    - name: Install Defender daemonset YAML
      redhat.openshift.k8s:
        state: present
        src: defender-ds.yaml
      register: result

    - name: Display deployment result
      debug:
        msg: "Defender DaemonSet deployment result: {{ result }}"
